### ISSUE TITLE
add to list of repositories used by layman

### ISSUE THREAD

**Issue by pavlix** [rafspiny/enlightenment-live#1]
We talked about it on IRC but I want to track it here so we don't forget to do it as soon as possible.

I recently added the *fedora* overlay and the following links show how that worked.

https://bugs.gentoo.org/show_bug.cgi?id=593318

https://github.com/gentoo/api-gentoo-org/pull/10/commits/bad35067a568ee532f024ce860fc9b7e89a02b4a

**Comment by rafspiny** [comment]
Thanks @pavlix.
I'll start adding the ebuilds for the latest stable release and fix the current one tonight.

Thank you

**Comment by rafspiny** [comment]
It is on its way.

https://github.com/gentoo/api-gentoo-org/pull/12
https://bugs.gentoo.org/show_bug.cgi?id=594132

**Comment by pavlix** [comment]
https://github.com/gentoo/api-gentoo-org/commit/93e6c23d175e653db54d364f96c345dfe98ce50f
