### ISSUE TITLE
efl-9999 build fails because libspectre is not found

### ISSUE THREAD

**Issue by Randl** [rafspiny/enlightenment-live#10]
Probably, it should be added to dependencies.
I'll add logs and use flags later if needed.

**Comment by rafspiny** [comment]
I aligned the efl-9999 to the use flag list of efl-1.8.1
[EFL-1.18.1]( https://github.com/rafspiny/enlightenment-live/blob/master/dev-libs/efl/efl-1.18.1.ebuild)

I will push the changes tomorrow.

Thanks for highlighting

**Comment by Randl** [comment]
@rafspiny also I had to install libraw. 

And I still couldn't install efl+enlightenment 9999 version. Unfortunately, I have already deleted logs and installed version from different overlay ( https://github.com/tokiclover/bar-overlay ).

In addition, 1.8.1 and 1.8.0 version both fail checksum verification (as far as I understand no checksum provided)

**Comment by Randl** [comment]
I recalled. `--enable-i-really-know-what-i-am-doing-and-that-this-will-probably-break-things-and-i-will-fix-them-myself-and-send-patches-aba` [here](https://github.com/rafspiny/enlightenment-live/blob/master/dev-libs/efl/efl-9999.ebuild#L227) is wrong, it should be `--enable-i-really-know-what-i-am-doing-and-that-this-will-probably-break-things-and-i-will-fix-them-myself-and-send-patches-abb` I believe

**Comment by rafspiny** [comment]
@Randl The last one is already corrected in the pull request #11 
I am checking the checksum right now

**Comment by rafspiny** [comment]
Closing this and moving the missing Manifest files into #12
