### ISSUE TITLE
Upstream moved meson into a new category

### ISSUE THREAD

**Issue by joostruis** [rafspiny/enlightenment-live#108]
https://github.com/gentoo/gentoo/tree/master/dev-build/meson

**Comment by skellr** [comment]
The meson eclass lists meson as a BDEPEND.  Can the dependency simply be removed from the ebuilds and let the eclass handle it?

**Comment by rafspiny** [comment]
Indeed. I adjusted the category in the ebuild files. It should be moved to BDEPEND indeed.

**Comment by rafspiny** [comment]
Done. Moved to BDEPEND. Please do feel free to close the issue @joostruis : )

**Comment by joostruis** [comment]
Closing, thanks all!
