### ISSUE TITLE
update Gentoo Wiki page for Enlightenment

### ISSUE THREAD

**Issue by pavlix** [rafspiny/enlightenment-live#2]
The current version of the Gentoo Wiki refers to https://github.com/okias/ixit for the ebuilds that we have moved to this new overlay and it doesn't include the new ebuilds by @dirk-olmes and @rafspiny.

https://wiki.gentoo.org/wiki/Enlightenment

**Comment by pavlix** [comment]
I have switched `ixit` to `enlightenment-live` in the wiki but it certainly needs an update regarding enlightenment versions.

**Comment by rafspiny** [comment]
Just made some changes.

**Comment by pavlix** [comment]
I removed myself as a point of contact and added GitHub instead, keeping your name after GitHub in case someone wants to speak to the maintainer directly. I will certainly try to help anyone who contacts me but I can no longer provide the support of a person with knowledge the ebuilds. Please modify to your needs.

**Comment by pavlix** [comment]
I also think that Gentoo Wiki shouldn't focus on versions that nobody cares about. In my opinion it should start with a stable version in Gentoo, continue with the most useful versions provided by overlays. But first of all I'm no longer following the development and I don't have a strong opinion on that, leaving that up to your consideration.

**Comment by pavlix** [comment]
And if you want to provide the contents of package.keywords, the `--autounmask-write` should probably go. See also #8.

**Comment by pavlix** [comment]
Gentoo Wiki speaks about EFL 1.18.1, Enlightenment 0.21.2, Terminology 0.9.1 as parts of enlightenment-live overlay. Terminology 0.9.1 probably was in ixit and was removed when it got to the official tree. This part should also be changed to reflect the current reality.

**Comment by rafspiny** [comment]
TODO list
- [ ] Use --automask-write instead
- [ ] Removing terminology 0.9.1 ebuild
- [ ] Update the section about apps
