### ISSUE TITLE
efl ebuilds refuse to emerge - "efl requires a C++ compiler got  g++"

### ISSUE THREAD

**Issue by Muffindrake** [rafspiny/enlightenment-live#22]
Greetings. The above error message greets me any time I attempt to emerge any dev-libs/efl 1.18.0 - 1.18.2.

All relevant information contained here:

https://gist.github.com/Muffindrake/50243cfd0ce9ae77d6df5635c8798707

(contains config.log now)

**Comment by rafspiny** [comment]
Thanks! I will have a look at it in a couple of hours.

**Comment by Muffindrake** [comment]
This is likely an issue stemming from upstream, as I am unable to emerge ANY efl ebuilds from either the gentoo tree or this overlay using GCC 5.4.0 (I have not tested other gcc versions).

However, I am able to emerge the library and other reliant ebuilds if I use clang instead (3.9.0), although without lto, as that causes build failures. This holds for efl-9999, enlightenment-9999 and terminology-9999 from this overlay.

Since this is more than likely an upstream problem *(or with some indeterminate probability a misconfiguration on my end)*, I'm partial to closing this issue, unless there's anything useful to be added here in a timely manner.

**Comment by Muffindrake** [comment]
I've had a little bit of a talk with raster on the #e IRC channel in Freenode. The issue turned out to be that $CXX was set (which is something that you may do when switching compilers ...), which interacted badly with this part of the configure script:

    # We should be using ${CXX} here, but there is a bug in
    # autotools macro and CXX is always set to g++ even if
    # it's not found. So we are using an internal variable
    # that does the work for now, may get broken in the future.
    if test "x${ac_ct_CXX}" = "x" -a "x${CXX}" = "xg++"; then
        AC_MSG_ERROR([efl requires a C++ compiler got ${ac_ct_CXX}
        and ${CXX}.])
    fi

Making sure $CXX is not set fixes the configure failure with gcc on my machine.

**Comment by rafspiny** [comment]
I read the chat with raster on IRC. I guess we can close the issue here then.

Thanks

**Comment by igel-kun** [comment]
err, it would be cool to know how the permanent fix for this issue looks like, for others (like me) having the same problem. My temporary fix is to prepend `ac_ct_CXX=${CXX}` to the mentioned configure block via a user-patch, which works fine but just seems wrong and dirty to me...
