### ISSUE TITLE
Same problem of issue #26, aready present.

### ISSUE THREAD

**Issue by dorvan** [rafspiny/enlightenment-live#27]
1-  =x11-wm/enlightenment-9999 version, does not require 9999 version of deps.
2- efl ebuild does not install missing deps like librsvg.
3- libsrvg depends on pango, from official ebuild seems non compile correctly. it's possible to have an USE to disable libsrvg dep?

**Comment by rafspiny** [comment]
Will fix 1 and 2 tonight.
About the 3rd one...libsrvg is really needed. I had a talk with Raster over IRC about this. I would prefer to keep it this way.
For the moment I'll make an exception for the 9999 version, but not for the stable ones.

**Comment by dorvan** [comment]
ok, for the stable (? ...also unstable I think, excluding git 9999 version ) I have to retry after the fix. Thanks. On Raster work, it's basic maintain the version alignment of all deps, due to save mental sanity.
