### ISSUE TITLE
efl-9999 fails to build because systemd is not disabled 

### ISSUE THREAD

**Issue by samis** [rafspiny/enlightenment-live#54]
I do not use systemd on my system and as such it is not installed and the systemd USE flag is not set. However, building current efl-9999 fails with the message that systemd support was requested and not present.

**Comment by rafspiny** [comment]
Hi Samis,
PR #55 should fix that. Tonight I will try it on a non systemd system before merging.

**Comment by rafspiny** [comment]
Hi @samis , I was unable te test it on a non systemd system. If this commit does not help, could you pastbin your emerge log?

**Comment by samis** [comment]
works now
