### ISSUE TITLE
Variable name mismatch in efl-9999.ebuild

### ISSUE THREAD

**Issue by jblandrum** [rafspiny/enlightenment-live#59]
The efl-9999.ebuild file has a variable naming error that causes many dependencies not to be pulled in by efl

line 39: COMMON_DEP="

line 165: ${COMMON_DEPEND}

**Comment by rafspiny** [comment]
This should be fixed by #60

**Comment by rafspiny** [comment]
Double checked in a Gentoo VM and working. Closing this one.
