### ISSUE TITLE
Verify live ebuilds

### ISSUE THREAD

**Issue by rafspiny** [rafspiny/enlightenment-live#6]
Need to check if they are working. If not fix them

**Comment by pavlix** [comment]
Just a related question, would it be possible to set up continuous integration for those builds? I'd be interested in the same for other repositories as well.

**Comment by rafspiny** [comment]
I was thinking to use Travis for this. 
mrueg have already done [something ](https://github.com/mrueg/mrueg-overlay/blob/master/.travis.yml) in this direction. The script run repoman on an ebuild.

**Comment by rafspiny** [comment]
Just fixed efl-9999, still missing enlightenment-9999
Not pushed yet.

- [x] efl-9999
- [ ] enlightenment-9999

**Comment by pavlix** [comment]
@rafspiny Yeah, repoman would be good, but what about also building the packages? I would use that for other overlays as well.

**Comment by rafspiny** [comment]
Moving the discussion to issue #14 
The ebuild for 9999 are working now
