### ISSUE TITLE
EFL won't compile funtoo1.3

### ISSUE THREAD

**Issue by CaptFrito** [rafspiny/enlightenment-live#64]
**/var/tmp/portage/dev-libs/efl-9999/temp/build.log**

GIT update -->
   repository:               https://git.enlightenment.org/core/efl.git
   at the commit:            03936c05131985a683967abc9cc1aa5ad88ff53a
>>> Source unpacked in /var/tmp/portage/dev-libs/efl-9999/work
>>> Preparing source in /var/tmp/portage/dev-libs/efl-9999/work/efl-9999 ...
 * Running eautoreconf in '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999' ...
/bin/grep: configure.??: No such file or directory
/bin/grep: configure.??: No such file or directory
/bin/grep: configure.??: No such file or directory
/bin/grep: configure.??: No such file or directory
/bin/grep: configure.??: No such file or directory
/bin/grep: configure.??: No such file or directory
 * Running aclocal ...
 [ !! ]

 * Failed Running aclocal !
 *

**Comment by rafspiny** [comment]
I believe this is due to #63 
EFL has now switched to meson. I already have a working meson ebuild for EFL, but I need to polish it before pushing.

**Comment by rafspiny** [comment]
@CaptFrito #65 Should have fixed this. Are you able to confirm?

**Comment by CaptFrito** [comment]
Unfortunately it didn't get very far. It seems this requires gstreamer 0.10. I have media-libs/gstreamer-1.14.4 installed (media-libs/gstreamer-0.10.36-r2 is available in portage)

I tried to attach my build.log file but github keeps rejecting it as unsupported file type (i tried several ways)

**Comment by CaptFrito** [comment]
Here is that build.log file

**Comment by rafspiny** [comment]
@CaptFrito I can't see any attachment. Can you pastebin it?

**Comment by CaptFrito** [comment]
ok:
https://pastebin.com/ZccQchAs

**Comment by rafspiny** [comment]
@CaptFrito I see the problem. I incorrectly handled the gstreamer use flag.
In the __emotion-loaders-disabler__ array, only the *gstreamer1* value should be impacted by the `gstreamer` use flag and not both *gstreamer1* and *gstreamer* values.

For the sake of clarity, the *gstreamer* value would not be able to be enabled at all, thus it will always be present in the __emotion-loaders-disabler__ array

A fix is on its way with #66

**Comment by rafspiny** [comment]
@CaptFrito The gstreamer issue has been finally addressed in #68

**Comment by CaptFrito** [comment]
I seem to be having trouble accessing git. I did sync portage and layman. From the most recent build log:

 * Fetching https://git.enlightenment.org/core/efl.git ...
git fetch https://git.enlightenment.org/core/efl.git +HEAD:refs/git-r3/HEAD
fatal: unable to access 'https://git.enlightenment.org/core/efl.git/': The requested URL returned error: 503
 * ERROR: dev-libs/efl-9999::enlightenment-live failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI

**Comment by rafspiny** [comment]
@CaptFrito There are problems with the servers. You may try to temporary alt the ebuild and poitn to github. Something like this:
> EGIT_REPO_URI="https://github.com/enlightenment/${PN}.git"

**Comment by CaptFrito** [comment]
Okay, compiles now. Thank you for your work on this. The funtoo portage ebuilds are ancient (and broken).

**Comment by rafspiny** [comment]
Thanks to you! Please feel free to report any other issue you may find.
Closing the issue now.
