### ISSUE TITLE
Add Enlightenment app ebuilds

### ISSUE THREAD

**Issue by rafspiny** [rafspiny/enlightenment-live#7]
It may be interesting to add ebuilds for Enlightenmetn apps.
Need to discuss this on IRC gentoo-e chanel

**Comment by mpkh** [comment]
Add Terminology please, in tree ebuild is broken.

**Comment by rafspiny** [comment]
Please @mpkh, can you give more details?
If it is broken, I will add an ebuild for terminology-0.9.1 in this overlay tonight

**Comment by rafspiny** [comment]
Still need to add another wave of apps

**Comment by dorvan** [comment]
consider [#25](https://github.com/rafspiny/enlightenment-live/issues/25) in the process
