### ISSUE TITLE
Failed build on gentoo stable 

### ISSUE THREAD

**Issue by dkuchay** [rafspiny/enlightenment-live#76]
Thank you for posting this project. Ran in to a problem while emerging.

The following files are missing:
 *
 *   /usr/lib64/python2.7/site-packages/gi/overrides/IBus.pyc
 *   /usr/lib64/python2.7/site-packages/gi/overrides/IBus.pyo
 *   /usr/lib64/python3.6/site-packages/gi/overrides/__pycache__/IBus.cpython-36.opt-2.pyc
 * Please either fix the upstream build system to byte-compile Python modules
 * correctly, or call python_optimize after installing them.  For more
 * information, see:
 * https://wiki.gentoo.org/wiki/Project:Python/Byte_compiling
 *
 * One or more compressed files were found in docompress-ed directories.
 * Please fix the ebuild not to install compressed files (manpages,
 * documentation) when automatic compression is used:
 *
 *   /usr/share/man/man5/00-upstream-settings.5.gz
 *   /usr/share/man/man5/ibus.5.gz
 *   /usr/share/man/man7/ibus-emoji.7.gz
 *   /usr/share/man/man1/ibus.1.gz
 *   /usr/share/man/man1/ibus-daemon.1.gz
 *   /usr/share/man/man1/ibus-setup.1.gz

Further down:

 * ERROR: dev-libs/efl-9999::enlightenment-live failed (configure phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 4162:  Called meson_src_configure
 *   environment, line 3182:  Called die
 * The specific snippet of code:
 *       tc-env_build "$@" || die
 *
 * If you need support, post the output of `emerge --info '=dev-libs/efl-9999::enlightenment-live'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/efl-9999::enlightenment-live'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/efl-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/efl-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'
 * S: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'

Please let me know if I can provide more. I set up keywords and use files. Setting up new system in bootstrap currently and after doing dispatch-conf I had to guess on the compositor so I added "X wayland" to use section within /etc/portage/make.conf

**Comment by rafspiny** [comment]
Hi, I am afraid what you posted is not very clear.
My understanding of this is that there may be a mishandled dependency on ibus.

It would help if you can post (through pastebin) the output of the following commands:
> emerge --info '=dev-libs/efl-9999::enlightenment-live'

> emerge -v '=dev-libs/efl-9999::enlightenment-live'

I would be able, then, to help properly fix anything wrong in the overlay.
Thanks for the feedback

**Comment by dkuchay** [comment]
First requested item:
https://pastebin.com/nV2w7iCp

Second item:
https://pastebin.com/CFdaRnf3

I was installing Gentoo to a laptop following Sakaki's Gentoo EFI guide when I ran in to your repo. I am not a Gentoo expert but want to learn. Old E fan from back in DR17 days and cant believe you have entrance working!! I attempted to deviate mid install to bring your repo in and get enlightenment. Was hoping for entrance but her method does kinda hard code in Plymouth as far as I know. I tried several flags for use and keywords including copying in from your example folder. Erased tried again and erased. I decided I couldn't wait so I just chose a gnome profile but the oddest thing happened after the completed. I reboot and I am on a text system with Plymouth installed. Bet I ran out of ram. I am using her efi stub kernel on a usb trick so I am not sure how much I can deviate and still use her kernel build tools. If its possible I would love to support your work. Thank you for making available all the E apps! I would like to write a tutorial on how one could do part Sakaki's guide but then deviate and go with enlightenment. Do you think its possible?

Thank you for your willingness to help!!!

**Comment by rafspiny** [comment]
Hi,
I skimmed the files and it looks like you **turned ON** all the USE flags.
You should choose what you need. That's what the message is saying.

Probably, removing `fbcon` and making a choice between `opengl` and the pair `egl` and `gles` will allow you to move forward and compile efl.
I also just worked on lifting the constraint between gles and sdl. It was merged this morning.

**Comment by dkuchay** [comment]
Thank you very much! I am one step further along. Removed fbcon, gles and egl from the use flags for enlightenment and am now trying to get past elogind or systemd. May I inquire to how necessary systemd is? I compiled kernel with openrc support and would rather not bring in systemd if I didnt have to. Is it possible to use elogind, eudev with openrc? End goal is a system that boots with entrance showing login screen.

**Comment by dkuchay** [comment]
On a whim I erased systemd use flag and am able to get building started. EFL fails on static libs vg_common_json.c indicating it has no LOTnode members named Keypath. node->keypath results in no member named *keypath*. The configure script passed dependency checking and this is a nina error. This time I will await your reply before trying to go forward. Thank you in advance!

**Comment by dkuchay** [comment]
backed up and re-approached. Installed systemd and now I see the same blocks that I had before installing systemd. sys-fs/udev is getting pulled in but it wont go any further because systemd blocks. gentoo-systemd-integration also bocks udev but its indicated as needed even after I manually removed it and tried re emerging your repo -core. I tried installing without systemd for half the day and was getting nowhere. Now that I have installed systemd its showing me the same circular blocks. 

Is it possible to use your repo without sytemd? If so please indicate how in the readme. As I understand through research we are limiting ourselves to not being able to use wayland by not using systemd. Is that the only restriction? Did you build entrance to rely on wayland?

**Comment by rafspiny** [comment]
Please, if you would like me to help, you have to post the output of the commands. Otherwise, it's very difficult for me to understand the problem and come up with a solution.

I will need the following output
> emerge --info '=dev-libs/efl-9999::enlightenment-live'
> emerge -v '=dev-libs/efl-9999::enlightenment-live'

To answer your second question about systemd. I was using it without systemd till early-2019. Then I switched to systemd. Honestly, I do not think there is a particular reason why it should not work without systemd.
It is true that I did not try it with openrc recently, So, it is possible that I introduced some bugs for non systemd systems.

If you want more information on e and gentoo you can also check out these two channels on IRC (freenode):
#e and #gentoo-e

**Comment by dkuchay** [comment]
First command:

https://pastebin.com/fiy4MCLx

Second command:

https://pastebin.com/t712CffK

When I saw your repo I was excited but saw that there was not enough information for me to proceed. I saw vague mention of systemd in keywords and went on utilizing openrc without negative mentions present. 

If you are willing to support open-rc please do not reply to this with anything other than awaiting your next update. I wish to back up again and reinstall without systemd. You have another neat gadget "Convertible". Again, I like your work. Did you switch to systemd for the development of that tool? Just curious. 


Again I would like to develop a guide for others to install Gentoo and to hopefully get a working Enlightenment full with apps and entrance login. I very much appreciate your help. I will use paste bin with these commands once I get back to open-rc. I will emerge to a default text profile and then add your repo to emerge and see how far I get. If I hit a wall I will report with two pastebin links and a simple description to what happened. 

Thank you again!

**Comment by rafspiny** [comment]
Regarding your logs. You have a circular dependency.
This is not related to my repo. It is tied to systemd per se.
You can also find other examples of this specific circular dependency on the Gentoo forum:
* [systemd-problems-1](https://forums.gentoo.org/viewtopic-t-1082152-start-0.html)
* [systemd-problems-2](https://forums.gentoo.org/viewtopic-t-1081824-start-0.html)

Coming to the support for openrc.
Indeed, there are no problems reported so far abuot openrc support so far.
I would need the output of `emerge -v '=dev-libs/efl-9999::enlightenment-live'` without the systemd use flag, to assist you with the support for openrc and that error about **keypath** you were talking about.

It would be nice if you can act as a tester for openrc. So that I can investigate if the support for openrc is indeed broken. I have not used it for a very long time. 
All my machines nowadays use systemd.

**Comment by dkuchay** [comment]
I just re did my filesystems via ssh to the target and was hoping you would ask that questions. I just started a bootstrap for installing basic toolchain on new attempt. Yes, I would love to! Thank you for all of the offered links. I will get on irc. Based on how the guide I am following is written (does bootstrap twice) I will be getting back to you about this time tomorrow with emerge results once I hit a wall. Cheers!

**Comment by dkuchay** [comment]
Started over with mkfs over existing partitions and installed base system last night.

https://pastebin.com/niSgSkUF   Ecrire log

https://pastebin.com/cmzgGv2r  everge --info...

https://pastebin.com/iyNaHF38  everge -v....


So I varied only by one step and I was able to build efl. Apps required with slight additions to /etc/portage/package.accept_keywords/enlightenment-9999 
additions:
=dev-util/espionage-9999 **
=media-video/rage-9999 **
=sys-process/evisum-9999 **

During installation sakaki has one tool I brought in after emerging @world with base profile. This was my one deviation from how I installed last time. Efitools caused a lot of things from parts of x11 to drm and 110 other packages on top of. Normally I would have emerged her efitools before emerging at world and not as much would have come in. 

I was able to get through efl with one hiccup on libXpresent. Had to install libXpresent and emerge -av enlightenment-core-9999 again. Everything else went well. The above additions came at time of aiming at enlightenment-apps-9999. Going to try aiming at dev now but I am happy to say that aside from ercire most things went well. Have not started enlightenment yet but its up to you on ecrire but I could technically close this issue. It has installed.

**Comment by dkuchay** [comment]
installed as much as I could. Most apps and dev too. After a few reboots and getting services up like connmand, acpid, etc I am no longer able to start enlightenment. Several times I get eina errors asking me to copy and paste in to terminal a 15 line or so aiming at /us/lib64/libeldbus.so.1 with hex adresses following in to terminal to fix. 3 times of that and now things are not working as well as they were on installation. What commands can I run to be of help?

**Comment by dkuchay** [comment]
Please disregard. x11-server did not pull in from base profile after emerging to enlightenment-live repo. Once x11-server was emerged it ran for a few times before realizing xterm was not installed. After emerging xterm it seems to be working again. How can one enable entrance on open-rc?
