### ISSUE TITLE
Need an update on the dev-libs/efl-9999:enlightenment-live USE flags

### ISSUE THREAD

**Issue by vokiel-too** [rafspiny/enlightenment-live#83]
I went through the steps to have it built successfully with:
- Masking >=lua-2.3.6-r2, the build requires lua5.2
- Emerging libheif with --oneshot, also seems to be required.

Not sure if what I set is a runnable environment yet, I still need to see if I can use Entrance with what I have. Things are quite different from the stable ebuild, there's no elogind for instance. Also, drm seems to require Wayland

Could we have an update on the examples?

I did:

dev-libs/efl-9999::enlightenment USE="X bmp connman eet fontconfig gif glib gstreamer harfbuzz ibus ico jpeg2k nls opengl pdf ppm psd pulseaudio sdl sound ssl svg tiff webp xml"

And then x11-wm/enlightenment was built with pam.

**Comment by rafspiny** [comment]
Hi, thanks for reporting.
Let me go in order to your points:

* Lua dependency: I need to check that.
* libheif: It was actually missing from the dependency. I did not notice it. I have an MR open to fix that. [MR here](https://github.com/rafspiny/enlightenment-live/pull/84)
* Wayland needed for DRM: I am not sure it is the case. I have DRM without involving wayland. I will double check later. If you have any log on this one, it would speed the process up.
* PAM: There is a `PAM` user flag for `x11-wm/enlightenment` that is not enforced. You shall be able to control it.

**Comment by rafspiny** [comment]
I am gonna close this one after releasing the fix for libheif.

Please create another issue with details and logs if you wish me to log further into something else.

**Comment by vokiel-too** [comment]
Sounds good, I'll test the build with drm and luajit.

Everything worked fine on starting an Enlightenment session, that said I'm using SDDM to do so.

**Comment by vokiel-too** [comment]
With drm -wayland:

<pre># sudo emerge --ask efl

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies /

!!! Problem resolving dependencies for dev-libs/efl
... done!

!!! The ebuild selected to satisfy "efl" has unmet requirements.
- dev-libs/efl-9999::enlightenment-live USE="X bmp connman drm eet fontconfig gif glib gstreamer harfbuzz ibus ico jpeg2k luajit nls opengl pdf ppm psd pulseaudio sdl sound ssl svg tiff webp xim -avahi -dds -debug -doc -egl -eo -example -fbcon -fribidi -gles -gnutls -hyphen -json -libuv -physics -pixman -postscript -raw -scim -systemd -test -tga -tslib -unwind -v4l -vlc -vnc -wayland -xcf -xine -xpm -xpresent" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    drm? ( wayland )

  The above constraints are a subset of the following complete expression:
    drm? ( wayland ) fbcon? ( !tslib ) gles? ( any-of ( X wayland ) egl ) ibus? ( glib ) opengl? ( any-of ( X sdl wayland ) ) pulseaudio? ( sound ) vnc? ( X fbcon ) wayland? ( any-of ( egl opengl gles ) ) xim? ( X )
</pre>

**Comment by vokiel-too** [comment]
@rafspiny  The luajit flag seems to be causing issues on the build:

<pre>
dev-libs/efl-9999::enlightenment-live was built with the following:
USE="X bmp connman eet fontconfig gif glib gstreamer harfbuzz heif ibus ico jpeg2k nls opengl pdf ppm psd pulseaudio sdl sound ssl svg tiff webp xim -avahi -dds -debug -doc -drm -egl -eo -example -fbcon -fribidi -gles -gnutls -hyphen -json -libuv -luajit -physics -pixman -postscript -raw -scim -systemd -test -tga -tslib -unwind -v4l -vlc -vnc -wayland -xcf -xine -xpm -xpresent" ABI_X86="(64)"

# sudo emerge --ask efl

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   *] dev-libs/efl-9999  USE="luajit*" 
</pre>

And then:

<pre>
meson.build:1:0: ERROR: Options "luajit" are not in allowed choices: ", lua, cxx, mono"

A full log can be found at /var/tmp/portage/dev-libs/efl-9999/work/efl-9999-build/meson-logs/meson-log.txt
 * ERROR: dev-libs/efl-9999::enlightenment-live failed (configure phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 4329:  Called meson_src_configure
 *   environment, line 3463:  Called die
 * The specific snippet of code:
 *       "${mesonargs[@]}" ) || die
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/efl-9999::enlightenment-live'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/efl-9999::enlightenment-live'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/efl-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/efl-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'
 * S: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'

>>> Failed to emerge dev-libs/efl-9999, Log file:

>>>  '/var/tmp/portage/dev-libs/efl-9999/temp/build.log'

 * Messages for package dev-libs/efl-9999:

 * ERROR: dev-libs/efl-9999::enlightenment-live failed (configure phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 4329:  Called meson_src_configure
 *   environment, line 3463:  Called die
 * The specific snippet of code:
 *       "${mesonargs[@]}" ) || die
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/efl-9999::enlightenment-live'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/efl-9999::enlightenment-live'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/efl-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/efl-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'
 * S: '/var/tmp/portage/dev-libs/efl-9999/work/efl-9999'
</pre>

**Comment by rafspiny** [comment]
Hi,

There was a problem with the semantic of the `luajit` flag. I was using it to also decide if lua bindings shall be built.
I fixed that in #87. Now `luajit` just decides which lua interpreter to have.
The `lua` useflag decides if lua bindings are being created or not.

Closing this one.
