### ISSUE TITLE
USE flag drm forces usage of wayland

### ISSUE THREAD

**Issue by vokiel-too** [rafspiny/enlightenment-live#86]
When adding drm to efl-9999:enlightenment-live, it forces usage of wayland:

<pre># sudo emerge --ask efl

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies /

!!! Problem resolving dependencies for dev-libs/efl
... done!

!!! The ebuild selected to satisfy "efl" has unmet requirements.
- dev-libs/efl-9999::enlightenment-live USE="X bmp connman drm eet fontconfig gif glib gstreamer harfbuzz ibus ico jpeg2k luajit nls opengl pdf ppm psd pulseaudio sdl sound ssl svg tiff webp xim -avahi -dds -debug -doc -egl -eo -example -fbcon -fribidi -gles -gnutls -hyphen -json -libuv -physics -pixman -postscript -raw -scim -systemd -test -tga -tslib -unwind -v4l -vlc -vnc -wayland -xcf -xine -xpm -xpresent" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    drm? ( wayland )

  The above constraints are a subset of the following complete expression:
    drm? ( wayland ) fbcon? ( !tslib ) gles? ( any-of ( X wayland ) egl ) ibus? ( glib ) opengl? ( any-of ( X sdl wayland ) ) pulseaudio? ( sound ) vnc? ( X fbcon ) wayland? ( any-of ( egl opengl gles ) ) xim? ( X )
</pre>

**Comment by rafspiny** [comment]
This is addressed in #89 

Feel free to reopen it if the fix does not work for you.
