### ISSUE TITLE
EFL builds fail

### ISSUE THREAD

**Issue by Username404-59** [rafspiny/enlightenment-live#98]
dev-libs/efl builds fail with
```
src/modules/ecore_evas/engines/drm/meson.build:6:18: ERROR: Unknown variable "engine_gl_drm"
```

**Comment by rafspiny** [comment]
Would you provide the use flags you used?

**Comment by Username404-59** [comment]
> Would you provide the use flags you used?

`drm glib vlc opengl egl gles wayland physics luajit`
